import Nav from "../components/Nav/Nav";
import NextNProgress from "nextjs-progressbar";
import Head from "next/head";
import { useState } from "react";

import { createGlobalStyle, ThemeProvider } from "styled-components";

const GlobalStyles = createGlobalStyle`
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Roboto', sans-serif;
  }

  body {
    background-color: ${(props) => props.theme.body};
    color: ${(props) => props.theme.text};
  }


  h1 {
    font-size: 3rem;
    text-align: center;
  }

  h3, h2{
    font-size: 1.3rem;
    text-align: center;
    
  } 

  h4{
    font-size: 1.2rem;
    
  }
  img {
    display: block;
    width: 100%;
  }
  button {
    font-size: 1rem;
    font-weight: 700;
    border: 0.05rem solid rgb(255, 255, 255);
    padding: 0.5rem 2rem;
    color: rgb(255, 255, 255);
    cursor: pointer;
    background-color: rgb(33, 37, 41);
  }
`;
const themes = {
  dark: {
    body: "rgb(21,23,30)",
    text: "white",
    span: "rgba(255,255,255,0.7)",

    border: "0.1rem solid rgb(255,255,255)",
    borderBackground: "rgb(255,255,255)",
  },
  light: {
    body: "white",
    text: "black",
    span: "rgba(255, 255, 255, 0.7);",

    border: "0.1rem solid rgb(0,0,0)",
    borderBackground: "rgb(0,0,0)",
  },
};

const MyApp = ({ Component, pageProps }) => {
  const [isDark, setIsDark] = useState(false);
  const theme = isDark ? themes.dark : themes.light;

  const toggleTheme = () => {
    setIsDark(!isDark);
  };

  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextNProgress color="red" height={3} showOnShallow={true} />
      <GlobalStyles theme={theme} />
      <ThemeProvider theme={theme}>
        <Nav toggleTheme={toggleTheme} isDark={isDark}/>
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
};

export default MyApp;
